/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

/**
 *
 * @author OliverAmitahi
 */

import com.sun.glass.events.KeyEvent;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.util.Timer;
import java.util.TimerTask;


public class Movimiento extends javax.swing.JFrame {

    /**
     * Creates new form Movimiento
     */
    static int numero = 0;
    private Image fondo;
    
    int x;
    int y;
    
    int casilla = 0;
    
    
    public Movimiento() {
        initComponents();
        dados.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        peon1 = new javax.swing.JLabel();
        dados = new javax.swing.JLabel();
        tirar = new javax.swing.JButton();
        tablero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        peon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/peon1.jpg"))); // NOI18N
        getContentPane().add(peon1);
        peon1.setBounds(60, 500, 50, 50);

        dados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/dados.gif"))); // NOI18N
        dados.setText("jLabel3");
        dados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dadosKeyPressed(evt);
            }
        });
        getContentPane().add(dados);
        dados.setBounds(230, 210, 170, 90);

        tirar.setText("TIRAR");
        tirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tirarActionPerformed(evt);
            }
        });
        getContentPane().add(tirar);
        tirar.setBounds(300, 310, 100, 30);

        tablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/bancopoly.jpg"))); // NOI18N
        getContentPane().add(tablero);
        tablero.setBounds(12, 13, 900, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dadosKeyPressed
        x = peon1.getX();
        y = peon1.getY();
        System.out.println(peon1.getLocation());

        switch(evt.getExtendedKeyCode())
        {
            case KeyEvent.VK_UP: peon1.setLocation(x, y-110); break;
            case KeyEvent.VK_DOWN: peon1.setLocation(x, y+110); break;
            case KeyEvent.VK_RIGHT: peon1.setLocation(x+110, y); break;
            case KeyEvent.VK_LEFT: peon1.setLocation(x-110, y); break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_dadosKeyPressed

    private void tirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tirarActionPerformed
        dados.enable(true);
            dados.setVisible(true);// TODO add your handling code here:

            int velocidad = 2;
        
        Timer time;
        TimerTask tarea;
        
        int velmil = velocidad * 1000;
        
        x = peon1.getX();
        y = peon1.getY();
        
        
        
        tarea = new TimerTask() {

            @Override
            public void run() {
               
                dados.enable(false);
                dados.setVisible(false);

                    numero = girar();
                
                for(int x = 1; x<=numero; x++)
                {
                        casilla = casilla + 1;
                        if(casilla <= 7)
                        {
                        pasoder();
                        }
                        if(casilla > 7 && casilla <=11)
                        {
                        pasoarriba();
                        }
                        if(casilla >11 && casilla <=18)
                        {
                        pasoizq();
                        }
                        if(casilla >18 && casilla <=22)
                        {
                        pasoabajo();
                            if(casilla == 22)
                            {
                            casilla = 0;
                            }
                        }
                }    
            
                
                
                
              }
        };
        
        time = new Timer();
        
//        time.scheduleAtFixedRate(tarea, velmil, velmil);
        time.schedule(tarea, velmil);

        

// TODO add your handling code here:
    }//GEN-LAST:event_tirarActionPerformed

        public void pasoder()
    {
        x = peon1.getX();
        y = peon1.getY();
        
        peon1.setLocation(x+110, y);      
    }
        
        public void pasoizq()
    {
        x = peon1.getX();
        y = peon1.getY();
        
        peon1.setLocation(x-110, y);      
    }
        public void pasoarriba()
    {
        x = peon1.getX();
        y = peon1.getY();
        
        peon1.setLocation(x, y-110);      
    }
        public void pasoabajo()
    {
        x = peon1.getX();
        y = peon1.getY();
        
        peon1.setLocation(x, y+110);      
    }
        
    
        
        
         public int girar()
    {
        Random randomGenerator = new Random();
        int randomInt = randomGenerator.nextInt(6);
        if(randomInt == 0)
        {
            girar();
        }
        else
        System.out.println("valor devuelto: " + randomInt);
        return randomInt;
    }

        
        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dados;
    private javax.swing.JLabel peon1;
    private javax.swing.JLabel tablero;
    private javax.swing.JButton tirar;
    // End of variables declaration//GEN-END:variables
}
