/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

/**
 *
 * @author OliverAmitahi
 */

import com.sun.glass.events.KeyEvent;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;


public class Movimiento extends javax.swing.JFrame {

    /**
     * Creates new form Movimiento
     */
    //
    //este es el numero que devuelve el dado despues de haber sido girado
    static int numero = 0;
    
    //posicion x,y del peon 1 en el tablero
    int x1;
    int y1;
    
    //posicion x,y del peon 2 en el tablero
    int x2;
    int y2;
    
    //posicion x,y del peon 3 en el tablero
    int x3;
    int y3;
    
    //posiciones logicas de los peones contra el tablero, nos sirve para comparar contra las casillas 
    int pos1 = 0;
    int pos2 = 0;
    int pos3 = 0;
    
    //variables jug, que sirven para mostrar el saldo de los jugadores
    double jug1 = 500;
    double jug2 = 500;
    double jug3 = 500;
    
    //casillas logicas del tablero, valor o representa que no ha sido comprada, 1 que le pertenece al jugador 1, 2 que le pertenece al jugador 2, y 3 que le pertenece al jugador 3
    int casillas[] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    
    
    //suma el valor de las propiedades adquirida VCs por cada jugador, nos sirve para obtener el impuesto en las casillas SAT
    int propiedad1 = 0;
    int propiedad2 = 0;
    int propiedad3 = 0;
    
    
    
    public Movimiento() {
        initComponents();
        dados.setVisible(false);
        tirar2.setVisible(false);
        tirar3.setVisible(false);
        tirar2.setEnabled(false);
        tirar3.setEnabled(false);
        txtJug1.setText("Q" + jug1);
        txtJug2.setText("Q" + jug2);
        txtJug3.setText("Q" + jug3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        peon1 = new javax.swing.JLabel();
        dados = new javax.swing.JLabel();
        tirar1 = new javax.swing.JButton();
        peon2 = new javax.swing.JLabel();
        peon3 = new javax.swing.JLabel();
        tirar2 = new javax.swing.JButton();
        tirar3 = new javax.swing.JButton();
        lblJug1 = new javax.swing.JLabel();
        lblJug2 = new javax.swing.JLabel();
        lblJug3 = new javax.swing.JLabel();
        txtJug1 = new javax.swing.JTextField();
        txtJug2 = new javax.swing.JTextField();
        txtJug3 = new javax.swing.JTextField();
        peon4 = new javax.swing.JLabel();
        peon5 = new javax.swing.JLabel();
        peon6 = new javax.swing.JLabel();
        btncupon = new javax.swing.JButton();
        tablero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        peon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pieza1.png"))); // NOI18N
        getContentPane().add(peon1);
        peon1.setBounds(50, 500, 40, 40);

        dados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/dados.gif"))); // NOI18N
        dados.setText("jLabel3");
        dados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dadosKeyPressed(evt);
            }
        });
        getContentPane().add(dados);
        dados.setBounds(230, 210, 170, 90);

        tirar1.setText("TIRAR PEON 1");
        tirar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tirar1ActionPerformed(evt);
            }
        });
        getContentPane().add(tirar1);
        tirar1.setBounds(300, 310, 120, 23);

        peon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pieza2.png"))); // NOI18N
        getContentPane().add(peon2);
        peon2.setBounds(90, 500, 40, 40);

        peon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pieza3.png"))); // NOI18N
        getContentPane().add(peon3);
        peon3.setBounds(70, 530, 70, 40);

        tirar2.setText("TIRAR PEON 2");
        tirar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tirar2ActionPerformed(evt);
            }
        });
        getContentPane().add(tirar2);
        tirar2.setBounds(300, 310, 120, 30);

        tirar3.setText("TIRAR PEON 3");
        tirar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tirar3ActionPerformed(evt);
            }
        });
        getContentPane().add(tirar3);
        tirar3.setBounds(300, 310, 120, 30);

        lblJug1.setText("Jugador 1");
        getContentPane().add(lblJug1);
        lblJug1.setBounds(320, 370, 48, 14);

        lblJug2.setText("Jugador 2");
        getContentPane().add(lblJug2);
        lblJug2.setBounds(320, 400, 60, 14);

        lblJug3.setText("Jugador 3");
        getContentPane().add(lblJug3);
        lblJug3.setBounds(320, 430, 48, 14);
        getContentPane().add(txtJug1);
        txtJug1.setBounds(390, 370, 80, 20);
        getContentPane().add(txtJug2);
        txtJug2.setBounds(390, 400, 80, 20);
        getContentPane().add(txtJug3);
        txtJug3.setBounds(390, 430, 80, 20);

        peon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pieza1.png"))); // NOI18N
        getContentPane().add(peon4);
        peon4.setBounds(280, 360, 40, 40);

        peon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pieza2.png"))); // NOI18N
        getContentPane().add(peon5);
        peon5.setBounds(280, 390, 40, 40);

        peon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pieza3.png"))); // NOI18N
        getContentPane().add(peon6);
        peon6.setBounds(280, 420, 70, 40);

        btncupon.setText("CUPON");
        btncupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuponActionPerformed(evt);
            }
        });
        getContentPane().add(btncupon);
        btncupon.setBounds(530, 360, 130, 30);

        tablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/bancopoly.jpg"))); // NOI18N
        getContentPane().add(tablero);
        tablero.setBounds(20, 30, 880, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //funcion que hace controlar al peon1, sobre todo el tablero con las flechas del teclado, solo sirvio de guia para determinar las posiciones
    private void dadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dadosKeyPressed
        x1 = peon1.getX();
        y1 = peon1.getY();
        System.out.println(peon1.getLocation());

        switch(evt.getExtendedKeyCode())
        {
            case KeyEvent.VK_UP: peon1.setLocation(x1, y1-110); break;
            case KeyEvent.VK_DOWN: peon1.setLocation(x1, y1+110); break;
            case KeyEvent.VK_RIGHT: peon1.setLocation(x1+110, y1); break;
            case KeyEvent.VK_LEFT: peon1.setLocation(x1-110, y1); break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_dadosKeyPressed

    
    
   //del boton tirar jugador 1 
    private void tirar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tirar1ActionPerformed
            dados.enable(true);
            dados.setVisible(true);// TODO add your handling code here:

            int velocidad = 2;
        
        Timer time;
        TimerTask tarea;
        
        int velmil = velocidad * 1000;
        
        
        //actualiza las posiciones del peon1
        x1 = peon1.getX();
        y1 = peon1.getY();
        
        
        
        tarea = new TimerTask() {

            @Override
            public void run() {
               
                dados.enable(false);
                dados.setVisible(false);
                
                
                //la variable numero obtiene el valor retornado del dado, para luego escalar las posiciones
                numero = girar();
                
                
                //validacion para avanzar deacuerdo a las casillas
                for(int x = 1; numero>=x; x++)
                {
                        pos1 = pos1 + 1;
                        if(pos1 <= 4)
                        {
                        pasoarriba();
                        }
                        if(pos1 > 4 && pos1 <=11)
                        {
                        pasoder();
                        }
                        if(pos1 >11 && pos1 <=15)
                        {
                        pasoabajo();
                        }
                        if(pos1 >15 && pos1 <=22)
                        {
                        pasoizq();
                            if(pos1 == 22)
                            {
                                //cuando de una vuelta completa se le asigna nuevamente 0 que es el inicio, y a su saldo se le suman 100 segun instrucciones del docto.
                            pos1 = 0;
                            jug1 = jug1 + 100;
                            }
                        }
                }
                        //empieza la validacion de la posicion actual del peon contra el estado de las casillas
                        //validacion de posiciones contra el estado "banco/ no comprado"
                
                        if(pos1 == 1 && casillas[1] == 0)
                        {
                            if(jug1>=130)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Huehuetenango por Q130.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug1 = jug1 - 130;
                                    casillas[1] = 1;
                                    propiedad1 = propiedad1 + 130;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos1 == 2 && casillas[2] == 0)
                        {
                            if(jug1>=100)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Quetzaltenango por Q100.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug1 = jug1 - 100;
                                    casillas[2] = 1;
                                    propiedad1 = propiedad1 + 100;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos1 == 3 && casillas[3] == 0)
                        {
                            if(jug1>=90)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Alta Verapaz por Q90.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug1 = jug1 - 90;
                                    casillas[3] = 1;
                                    propiedad1 = propiedad1 + 90;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        
                        if(pos1 == 5 && casillas[5] == 0)
                        {
                            if(jug1>=150)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Quiche por Q150.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug1 = jug1 - 150;
                                    casillas[5] = 1;
                                    propiedad1 = propiedad1 + 150;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }  
                            }
                        } 
                        if(pos1 == 6 && casillas[6] == 0)
                        {
                            if(jug1>=140)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Izabal por Q140.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug1 = jug1 - 140;
                                    casillas[6] = 1;
                                    propiedad1 = propiedad1 + 140;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                } 
                            }
                        } 
                        if(pos1 == 7 && casillas[7] == 0)
                        {
                            if(jug1>=50)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Peten por Q50.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug1 = jug1 - 50;
                                    casillas[7]= 1;
                                    propiedad1 = propiedad1 + 50;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos1 == 8 && casillas[8] == 0)
                        {
                            if(jug1>=190)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Fegua por Q190.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug1 = jug1 - 190;
                                    casillas[8] = 1;
                                    propiedad1 = propiedad1 + 190;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos1 == 9 && casillas[9] == 0)
                        {
                            if(jug1>=170)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Solola por Q170.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug1 = jug1 - 170;
                                    casillas[9]= 1;
                                    propiedad1 = propiedad1 + 170;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        
                        if(pos1 == 10 && casillas[10]== 0)
                        {
                            double impuesto = propiedad1 * 0.10;
                            jug1 = jug1 - impuesto;
                        } 
                        if(pos1 == 11 && casillas[11] == 0)
                        {
                            //descanzo
                        } 
                        if(pos1 == 12 && casillas[12]== 0)
                        {
                            if(jug1>=230)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar San Marcos por Q230.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug1 = jug1 - 230;
                                    casillas[12] = 1;
                                    propiedad1 = propiedad1 + 230;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                } 
                            }
                        } 
                        if(pos1 == 13 && casillas[13] == 0)
                        {
                            if(jug1>=250)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Baja Verapaz por Q250.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug1 = jug1 - 250;
                                    casillas[13]= 1;
                                    propiedad1 = propiedad1 + 250;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }   
                            }
                        } 
                        if(pos1 == 14 && casillas[14] == 0)
                        {
                            if(jug1>=175)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Empagua por Q175.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug1 = jug1 - 175;
                                    casillas[14] = 1;
                                    propiedad1 = propiedad1 + 175;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }   
                            }
                        } 
                        
                        if(pos1 == 15 && casillas[15] == 0)
                        {
                            pasoarriba();
                            pasoarriba();
                            pasoarriba();
                            pasoarriba();
                            pasoizq();
                            pasoizq();
                            pasoizq();
                            pasoizq();
                            pasoizq();
                            pasoizq();
                            pasoizq();
                            pos1 = 4;
                            jug1 = jug1 - 100;
                        } 
                        
                        if(pos1 == 16 && casillas[16]== 0)
                        {
                            JOptionPane.showMessageDialog(null, "Seleccione el Boton Cupon");  //cupon
                            btncupon.setEnabled(true);
                            
                        } 
                        
                        
                        if(pos1 == 17 && casillas[17]== 0)
                        {
                            if(jug1>=310)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Santa Rosa por Q310.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug1 = jug1 - 310;
                                    casillas[17] = 1;
                                    propiedad1 = propiedad1 + 310;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos1 == 18 && casillas[18]== 0)
                        {
                            if(jug1>=270)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Zacapa por Q270.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug1 = jug1 - 270;
                                    casillas[18] = 1;
                                    propiedad1 = propiedad1 + 270;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                } 
                            }
                        } 
                        if(pos1 == 19 && casillas[19]== 0)
                        {
                            if(jug1>=250)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Guatemala por Q250.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug1 = jug1 - 250;
                                    casillas[19] = 1;
                                    propiedad1 = propiedad1 + 250;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                } 
                            }
                        } 
                        
                        if(pos1 == 20 && casillas[20]== 0)
                        {
                            if(jug1>=390)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Jutiapa por Q390.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug1 = jug1 - 390;
                                    casillas[20] = 1;
                                    propiedad1 = propiedad1 + 390;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos1 == 21 && casillas[21] == 0)
                        {
                            double impuesto = propiedad1 * 0.10;
                            jug1 = jug1 - impuesto;
                        } 
                        
                          
                        for(int i = 1; i<=21; i++)
                        {
                            //validacion de posiciones contra el estado "jugador 2"
                           if(pos1 == i && casillas[i] == 2)
                            {
                                jug2 = jug2 + 50;
                                jug1 = jug1 - 50;
                            } 
                           //validacion de posiciones contra el estado "jugador 3"
                           if(pos1 == i && casillas[i] == 3)
                            {
                                jug3 = jug3 + 50;
                                jug1 = jug1 - 50;
                            } 
                        
                        }
               
               
               txtJug1.setText("Q" + jug1);
               txtJug2.setText("Q" + jug2);
               txtJug3.setText("Q" + jug3);
               tirar2.setVisible(true);
               tirar2.setEnabled(true);
               tirar1.setEnabled(false);
               tirar1.setVisible(false);
              }
        };
        
        time = new Timer();
        
//        time.scheduleAtFixedRate(tarea, velmil, velmil);
        time.schedule(tarea, velmil);

        

// TODO add your handling code here:
    }//GEN-LAST:event_tirar1ActionPerformed

    private void tirar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tirar2ActionPerformed
         dados.enable(true);
            dados.setVisible(true);// TODO add your handling code here:

            int velocidad = 2;
        
        Timer time;
        TimerTask tarea;
        
        int velmil = velocidad * 1000;
        
        
        //actualiza las posiciones del peon1
        x2 = peon2.getX();
        y2 = peon2.getY();
        
        
        
        tarea = new TimerTask() {

            @Override
            public void run() {
               
                dados.enable(false);
                dados.setVisible(false);
                
                
                //la variable numero obtiene el valor retornado del dado, para luego escalar las posiciones
                numero = girar();
                
                //validacion para avanzar deacuerdo a las casillas
                for(int x = 1; numero>=x; x++)
                {
                        pos2 = pos2 + 1;
                        if(pos2 <= 4)
                        {
                        pasoarribap2();
                        }
                        if(pos2 > 4 && pos2 <=11)
                        {
                        pasoderp2();
                        }
                        if(pos2 >11 && pos2 <=15)
                        {
                        pasoabajop2();
                        }
                        if(pos2 >15 && pos2 <=22)
                        {
                        pasoizqp2();
                            if(pos2 == 22)
                            {
                                //cuando de una vuelta completa se le asigna nuevamente 0 que es el inicio, y a su saldo se le suman 100 segun instrucciones del docto.
                            pos2 = 0;
                            jug2 = jug2 + 100;
                            }
                        }
                }
                        //empieza la validacion de la posicion actual del peon contra el estado de las casillas
                        //validacion de posiciones contra el estado "banco/ no comprado"
                
                        if(pos2 == 1 && casillas[1] == 0)
                        {
                            if(jug2>=130)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Huehuetenango por Q130.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug2 = jug2 - 130;
                                    casillas[1] = 2;
                                    propiedad2 = propiedad2 + 130;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos2 == 2 && casillas[2] == 0)
                        {
                            if(jug2>=100)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Quetzaltenango por Q100.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug2 = jug2 - 100;
                                    casillas[2] = 2;
                                    propiedad2 = propiedad2 + 100;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos2 == 3 && casillas[3] == 0)
                        {
                            if(jug2>=90)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Alta Verapaz por Q90.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug2 = jug2 - 90;
                                    casillas[3] = 2;
                                    propiedad2 = propiedad2 + 90;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        
                        if(pos2 == 5 && casillas[5] == 0)
                        {
                            if(jug2>=150)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Quiche por Q150.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug2 = jug2 - 150;
                                    casillas[5] = 2;
                                    propiedad2 = propiedad2 + 150;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }  
                            }
                        } 
                        if(pos2 == 6 && casillas[6] == 0)
                        {
                            if(jug2>=140)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Izabal por Q140.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug2 = jug2 - 140;
                                    casillas[6] = 2;
                                    propiedad2 = propiedad2 + 140;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                } 
                            }
                        } 
                        if(pos2 == 7 && casillas[7] == 0)
                        {
                            if(jug2>=50)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Peten por Q50.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug2 = jug2 - 50;
                                    casillas[7]= 2;
                                    propiedad2 = propiedad2 + 50;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos2 == 8 && casillas[8] == 0)
                        {
                            if(jug2>=190)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Fegua por Q190.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug2 = jug2 - 190;
                                    casillas[8] = 2;
                                    propiedad2 = propiedad2 + 190;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos2 == 9 && casillas[9] == 0)
                        {
                            if(jug2>=170)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Solola por Q170.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug2 = jug2 - 170;
                                    casillas[9]= 2;
                                    propiedad2 = propiedad2 + 170;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        
                        if(pos2 == 10 && casillas[10]== 0)
                        {
                            double impuesto = propiedad2 * 0.10;
                            jug2 = jug2 - impuesto;
                        } 
                        if(pos2 == 11 && casillas[11] == 0)
                        {
                            //descanzo
                        } 
                        if(pos2 == 12 && casillas[12]== 0)
                        {
                            if(jug2>=230)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar San Marcos por Q230.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug2 = jug2 - 230;
                                    casillas[12] = 2;
                                    propiedad2 = propiedad2 + 230;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                } 
                            }
                        } 
                        if(pos2 == 13 && casillas[13] == 0)
                        {
                            if(jug2>=250)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Baja Verapaz por Q250.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug2 = jug2 - 250;
                                    casillas[13]= 2;
                                    propiedad2 = propiedad2 + 250;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }   
                            }
                        } 
                        if(pos2 == 14 && casillas[14] == 0)
                        {
                            if(jug2>=175)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Empagua por Q175.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug2 = jug2 - 175;
                                    casillas[14] = 2;
                                    propiedad2 = propiedad2 + 175;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }   
                            }
                        } 
                        
                        if(pos2 == 15 && casillas[15] == 0)
                        {
                            pasoarribap2();
                            pasoarribap2();
                            pasoarribap2();
                            pasoarribap2();
                            pasoizqp2();
                            pasoizqp2();
                            pasoizqp2();
                            pasoizqp2();
                            pasoizqp2();
                            pasoizqp2();
                            pasoizqp2();
                            pos2 = 4;
                            jug2 = jug2 - 100;
                        } 
                        if(pos2 == 16 && casillas[16]== 0)
                        {
                            //cupon
                        } 
                        if(pos2 == 17 && casillas[17]== 0)
                        {
                            if(jug2>=310)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Santa Rosa por Q310.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug2 = jug2 - 310;
                                    casillas[17] = 2;
                                    propiedad2 = propiedad2 + 310;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos2 == 18 && casillas[18]== 0)
                        {
                            if(jug2>=270)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Zacapa por Q270.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug2 = jug2 - 270;
                                    casillas[18] = 2;
                                    propiedad2 = propiedad2 + 270;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                } 
                            }
                        } 
                        if(pos2 == 19 && casillas[19]== 0)
                        {
                            if(jug2>=250)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Guatemala por Q250.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug2 = jug2 - 250;
                                    casillas[19] = 2;
                                    propiedad2 = propiedad2 + 250;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                } 
                            }
                        } 
                        
                        if(pos2 == 20 && casillas[20]== 0)
                        {
                            if(jug2>=390)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Jutiapa por Q390.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug2 = jug2 - 390;
                                    casillas[20] = 2;
                                    propiedad2 = propiedad2 + 390;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos2 == 21 && casillas[21] == 0)
                        {
                            double impuesto = propiedad2 * 0.10;
                            jug2 = jug2 - impuesto;
                        } 
                        
                          
                        for(int i = 1; i<=21; i++)
                        {
                            //validacion de posiciones contra el estado "jugador 2"
                           if(pos2 == i && casillas[i] == 1)
                            {
                                jug1 = jug1 + 50;
                                jug2 = jug2 - 50;
                            } 
                           //validacion de posiciones contra el estado "jugador 3"
                           if(pos1 == i && casillas[i] == 3)
                            {
                                jug3 = jug3 + 50;
                                jug2 = jug2 - 50;
                            } 
                        
                        }
               
               
               txtJug1.setText("Q" + jug1);
               txtJug2.setText("Q" + jug2);
               txtJug3.setText("Q" + jug3);
               tirar3.setVisible(true);
               tirar3.setEnabled(true);
               tirar2.setEnabled(false);
               tirar2.setVisible(false);
              }
        };
        
        time = new Timer();
        
//        time.scheduleAtFixedRate(tarea, velmil, velmil);
        time.schedule(tarea, velmil);

        
    }//GEN-LAST:event_tirar2ActionPerformed

    private void tirar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tirar3ActionPerformed
         dados.enable(true);
            dados.setVisible(true);// TODO add your handling code here:

            int velocidad = 2;
        
        Timer time;
        TimerTask tarea;
        
        int velmil = velocidad * 1000;
        
        
        //actualiza las posiciones del peon1
        x3 = peon3.getX();
        y3 = peon3.getY();
        
        
        
        tarea = new TimerTask() {

            @Override
            public void run() {
               
                dados.enable(false);
                dados.setVisible(false);
                
                
                //la variable numero obtiene el valor retornado del dado, para luego escalar las posiciones
                numero = girar();
                
                //validacion para avanzar deacuerdo a las casillas
                for(int x = 1; numero>=x; x++)
                {
                        pos3 = pos3 + 1;
                        if(pos3 <= 4)
                        {
                        pasoarribap3();
                        }
                        if(pos3 > 4 && pos3 <=11)
                        {
                        pasoderp3();
                        }
                        if(pos3 >11 && pos3 <=15)
                        {
                        pasoabajop3();
                        }
                        if(pos3 >15 && pos3 <=22)
                        {
                        pasoizqp3();
                            if(pos3 == 22)
                            {
                                //cuando de una vuelta completa se le asigna nuevamente 0 que es el inicio, y a su saldo se le suman 100 segun instrucciones del docto.
                            pos3 = 0;
                            jug3 = jug3 + 100;
                            }
                        }
                }
                        //empieza la validacion de la posicion actual del peon contra el estado de las casillas
                        //validacion de posiciones contra el estado "banco/ no comprado"
                
                        if(pos3 == 1 && casillas[1] == 0)
                        {
                            if(jug3>=130)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Huehuetenango por Q130.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug3 = jug3 - 130;
                                    casillas[1] = 3;
                                    propiedad3 = propiedad3 + 130;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos3 == 2 && casillas[2] == 0)
                        {
                            if(jug3>=100)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Quetzaltenango por Q100.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug3 = jug3 - 100;
                                    casillas[2] = 3;
                                    propiedad3 = propiedad3 + 100;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos3 == 3 && casillas[3] == 0)
                        {
                            if(jug3>=90)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Alta Verapaz por Q90.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug3 = jug3 - 90;
                                    casillas[3] = 3;
                                    propiedad3 = propiedad3 + 90;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        
                        if(pos3 == 5 && casillas[5] == 0)
                        {
                            if(jug3>=150)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Quiche por Q150.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug3 = jug3 - 150;
                                    casillas[5] = 3;
                                    propiedad3 = propiedad3 + 150;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }  
                            }
                        } 
                        if(pos3 == 6 && casillas[6] == 0)
                        {
                            if(jug3>=140)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Izabal por Q140.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug3 = jug3 - 140;
                                    casillas[6] = 3;
                                    propiedad3 = propiedad3 + 140;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                } 
                            }
                        } 
                        if(pos3 == 7 && casillas[7] == 0)
                        {
                            if(jug3>=50)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Peten por Q50.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug3 = jug3 - 50;
                                    casillas[7]= 3;
                                    propiedad3 = propiedad3 + 50;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos3 == 8 && casillas[8] == 0)
                        {
                            if(jug3>=190)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Fegua por Q190.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug3 = jug3 - 190;
                                    casillas[8] = 3;
                                    propiedad3 = propiedad3 + 190;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos3 == 9 && casillas[9] == 0)
                        {
                            if(jug3>=170)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Solola por Q170.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug3 = jug3 - 170;
                                    casillas[9]= 3;
                                    propiedad3 = propiedad3 + 170;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        
                        if(pos3 == 10 && casillas[10]== 0)
                        {
                            double impuesto = propiedad3 * 0.10;
                            jug3 = jug3 - impuesto;
                        } 
                        if(pos3 == 11 && casillas[11] == 0)
                        {
                            //descanzo
                        } 
                        if(pos3 == 12 && casillas[12]== 0)
                        {
                            if(jug3>=230)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar San Marcos por Q230.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug3 = jug3 - 230;
                                    casillas[12] = 3;
                                    propiedad3 = propiedad3 + 230;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                } 
                            }
                        } 
                        if(pos3 == 13 && casillas[13] == 0)
                        {
                            if(jug3>=250)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Baja Verapaz por Q250.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug3 = jug3 - 250;
                                    casillas[13]= 3;
                                    propiedad3 = propiedad3 + 250;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }   
                            }
                        } 
                        if(pos3 == 14 && casillas[14] == 0)
                        {
                            if(jug3>=175)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Empagua por Q175.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug3 = jug3 - 175;
                                    casillas[14] = 3;
                                    propiedad3 = propiedad3 + 175;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }   
                            }
                        } 
                        
                        if(pos3 == 15 && casillas[15] == 0)
                        {
                            pasoarribap3();
                            pasoarribap3();
                            pasoarribap3();
                            pasoarribap3();
                            pasoizqp3();
                            pasoizqp3();
                            pasoizqp3();
                            pasoizqp3();
                            pasoizqp3();
                            pasoizqp3();
                            pasoizqp3();
                            pos3 = 4;
                            jug3 = jug3 - 100;
                        } 
                        if(pos3 == 16 && casillas[16]== 0)
                        {
                            //cupon
                        } 
                        if(pos3 == 17 && casillas[17]== 0)
                        {
                            if(jug3>=310)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Santa Rosa por Q310.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug3 = jug3 - 310;
                                    casillas[17] = 3;
                                    propiedad3 = propiedad3 + 310;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos3 == 18 && casillas[18]== 0)
                        {
                            if(jug3>=270)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Zacapa por Q270.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug3 = jug3 - 270;
                                    casillas[18] = 3;
                                    propiedad3 = propiedad3 + 270;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                } 
                            }
                        } 
                        if(pos3 == 19 && casillas[19]== 0)
                        {
                            if(jug3>=250)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Guatemala por Q250.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug3 = jug3 - 250;
                                    casillas[19] = 3;
                                    propiedad3 = propiedad3 + 250;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                } 
                            }
                        } 
                        
                        if(pos3 == 20 && casillas[20]== 0)
                        {
                            if(jug3>=390)
                            {
                                int ax = JOptionPane.showConfirmDialog(null, "Deseas Comprar Jutiapa por Q390.00");
                                if(ax == JOptionPane.YES_OPTION)
                                {
                                    jug3 = jug3 - 390;
                                    casillas[20] = 3;
                                    propiedad3 = propiedad3 + 390;
                                }
                                else if(ax == JOptionPane.NO_OPTION)
                                {
                                JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                                }
                            }
                        } 
                        if(pos3 == 21 && casillas[21] == 0)
                        {
                            double impuesto = propiedad3 * 0.10;
                            jug3 = jug3 - impuesto;
                        } 
                        
                          
                        for(int i = 1; i<=21; i++)
                        {
                            //validacion de posiciones contra el estado "jugador 2"
                           if(pos3 == i && casillas[i] == 2)
                            {
                                jug2 = jug2 + 50;
                                jug3 = jug3 - 50;
                            } 
                           //validacion de posiciones contra el estado "jugador 3"
                           if(pos3 == i && casillas[i] == 1)
                            {
                                jug1 = jug1 + 50;
                                jug3 = jug3 - 50;
                            } 
                        
                        }
               
               
               txtJug1.setText("Q" + jug1);
               txtJug2.setText("Q" + jug2);
               txtJug3.setText("Q" + jug3);
               tirar1.setVisible(true);
               tirar1.setEnabled(true);
               tirar3.setEnabled(false);
               tirar3.setVisible(false);
              }
        };
        
        time = new Timer();
        
//        time.scheduleAtFixedRate(tarea, velmil, velmil);
        time.schedule(tarea, velmil);

        

// TODO add your handling code here:
    }//GEN-LAST:event_tirar3ActionPerformed

    private void btncuponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuponActionPerformed
       
        int dato1, dato2;
            
        String cadena;
        String lista = "LIBRE_DE_CARCEL COBRE_100 PAGUE_100";
        Random azar = new Random();
 
        //genera numero al azar de la cadena
        dato1 = azar.nextInt(lista.length());
 
        // Verifica la posicion si es espacio vacio o letra
        if(lista.charAt(dato1) == ' ')
        {
            dato2 = ++dato1;
        }
        else
        {
            dato2 = dato1;
 
            while(dato1 - 1 >= 0 && lista.charAt(dato1 - 1) != ' ')
                dato1--;
        }
 
       // Ubica el final de la palabra
        while((dato2 + 1) <= lista.length())
        {
            if(lista.charAt(dato2) != ' ')
                dato2++;
            else
                break;
        }
 
        cadena = lista.substring(dato1, dato2);
        JOptionPane.showMessageDialog(null, (cadena));
        
        if("COBRE_100".equals(cadena)){
           jug1= jug1 + 100;
           txtJug1.setText("Q" +jug1);
        }
        else{      
        
    }//GEN-LAST:event_btncuponActionPerformed

    
    if("PAGUE_100".equals(cadena)){
           jug1= jug1 - 100;
           txtJug1.setText("Q" + jug1);
        }
        else{
        }

    
    if("LIBRE_DE_CARCEL".equals(cadena)){
           
        }
        else{
        }
        
    }        
    

    
        public void pasoder()
    {
        x1 = peon1.getX();
        y1 = peon1.getY();
        
        peon1.setLocation(x1+110, y1);      
    }
        
        public void pasoizq()
    {
        x1 = peon1.getX();
        y1 = peon1.getY();
        
        peon1.setLocation(x1-110, y1);      
    }
        public void pasoarriba()
    {
        x1 = peon1.getX();
        y1 = peon1.getY();
        
        peon1.setLocation(x1, y1-110);      
    }
        public void pasoabajo()
    {
        x1 = peon1.getX();
        y1 = peon1.getY();
        
        peon1.setLocation(x1, y1+110);      
    }
       
        
    
        
    public void pasoderp2()
    {
        x2 = peon2.getX();
        y2 = peon2.getY();
        
        peon2.setLocation(x2+110, y2);      
    }
        
        public void pasoizqp2()
    {
        x2 = peon2.getX();
        y2 = peon2.getY();
        
        peon2.setLocation(x2-110, y2);      
    }
        public void pasoarribap2()
    {
        x2 = peon2.getX();
        y2 = peon2.getY();
        
        peon2.setLocation(x2, y2-110);      
    }
        public void pasoabajop2()
    {
        x2 = peon2.getX();
        y2 = peon2.getY();
        
        peon2.setLocation(x2, y2+110);      
    }
        
    
        public void pasoderp3()
    {
        x3 = peon3.getX();
        y3 = peon3.getY();
        
        peon3.setLocation(x3+110, y3);      
    }
        
        public void pasoizqp3()
    {
        x3 = peon3.getX();
        y3 = peon3.getY();
        
        peon3.setLocation(x3-110, y3);      
    }
        public void pasoarribap3()
    {
        x3 = peon3.getX();
        y3 = peon3.getY();
        
        peon3.setLocation(x3, y3-110);      
    }
        public void pasoabajop3()
    {
        x3 = peon3.getX();
        y3 = peon3.getY();
        
        peon3.setLocation(x3, y3+110);      
    }
        
        
    
        
        
         public int aleatorio()
    {
        Random randomGenerator = new Random();
        int randomInt = randomGenerator.nextInt(6);
        if(randomInt == 0)
        {
            aleatorio();
        }
        else
        JOptionPane.showMessageDialog(null, "valor devuelto: " + randomInt);
        return randomInt;
    }
        
        public int girar()
    {
       int n = aleatorio();
       while(n == 0)
       {
           n = aleatorio();
       }
       return n;
    }

        
        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncupon;
    private javax.swing.JLabel dados;
    private javax.swing.JLabel lblJug1;
    private javax.swing.JLabel lblJug2;
    private javax.swing.JLabel lblJug3;
    private javax.swing.JLabel peon1;
    private javax.swing.JLabel peon2;
    private javax.swing.JLabel peon3;
    private javax.swing.JLabel peon4;
    private javax.swing.JLabel peon5;
    private javax.swing.JLabel peon6;
    private javax.swing.JLabel tablero;
    private javax.swing.JButton tirar1;
    private javax.swing.JButton tirar2;
    private javax.swing.JButton tirar3;
    private javax.swing.JTextField txtJug1;
    private javax.swing.JTextField txtJug2;
    private javax.swing.JTextField txtJug3;
    // End of variables declaration//GEN-END:variables
}
